#!/bin/bash
#subin_sv

usage(){
    echo "Usage: mtpclone [-m Music] [-p Pictues] [-f Full backup]";
    exit 1;
}

mtppath="/run/user/1000/gvfs/"
mtpname=`ls $mtppath | grep mtp`

if [ -z "$mtpname" ]
then
    echo "MTP device not found. Please connect your device and try again"
    usage
elif [ -z "$1" ]
then
    usage
else
    while getopts ":mpf" opt;
    do
        case $opt in 
            "m")
            echo "Trying to sync Android Music folder to $HOME/Music"
            START_TIME=$SECONDS;
            rsync --verbose --progress --omit-dir-times --no-perms --recursive --delete --update --exclude=".*" --exclude ".*/" "/run/user/1000/gvfs/$mtpname/Internal shared storage/Music/" "$HOME/Music"
            echo "Time elapsed: $((SECONDS-START_TIME)) seconds"
            ;;
            "p")
            echo "Trying to sync Android DCIM folder to $HOME/Pictures/MobileBackup"
            START_TIME=$SECONDS;
            rsync --verbose --progress --omit-dir-times --no-perms --recursive --delete --update --exclude=".*" --exclude ".*/" "/run/user/1000/gvfs/$mtpname/Internal shared storage/DCIM/" "$HOME/Pictures/MobileBackup"
            echo "Time elapsed: $((SECONDS-START_TIME)) seconds"
            ;;
            "f")
            echo "Trying to backup Android Internal Storage to /mnt/2827A0ED3C7B53AA"
            START_TIME=$SECONDS;
            tar --exclude='.*' --exclude='.*/' --exclude='Android' --exclude='Alarms' --exclude='Arrow' --exclude='com.*' --exclude='Download' --exclude='MagiskManager' --exclude='Movies' --exclude='Notifications' --exclude='Podcasts' --exclude='Ringtones' --exclude='ROM' -zcvf "/mnt/2827A0ED3C7B53AA/Android_backup_$(date '+%F').tar.gz" "/run/user/1000/gvfs/$mtpname/Internal shared storage"
            echo "Time elapsed: $((SECONDS-START_TIME)) seconds"
            ;;
            *)
            usage
            ;;
        esac
    done
    shift $((OPTIND-1))
fi